// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAlly.Data;

#nullable disable

namespace TravelAlly.Migrations
{
    [DbContext(typeof(TravelAllyContext))]
    [Migration("20230227174503_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TravelAlly.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Continent")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 51.507221999999999,
                            Lon = -0.1275,
                            Name = "London"
                        },
                        new
                        {
                            Id = 2,
                            Continent = 5,
                            Country = "France",
                            Lat = 48.864716000000001,
                            Lon = 2.3490139999999999,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 3,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 51.316366000000002,
                            Lon = -0.55783300000000002,
                            Name = "Woking"
                        },
                        new
                        {
                            Id = 4,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 51.26332,
                            Lon = -1.090735,
                            Name = "Basingstoke"
                        },
                        new
                        {
                            Id = 5,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 50.725555999999997,
                            Lon = -3.5269439999999999,
                            Name = "Exeter"
                        },
                        new
                        {
                            Id = 6,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 50.740690000000001,
                            Lon = -3.4671699999999999,
                            Name = "Pinhoe"
                        },
                        new
                        {
                            Id = 7,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 50.747,
                            Lon = -3.4129999999999998,
                            Name = "Cranbrook (Devon)"
                        },
                        new
                        {
                            Id = 8,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 50.798099999999998,
                            Lon = -3.1924999999999999,
                            Name = "Honiton"
                        },
                        new
                        {
                            Id = 9,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 50.7821,
                            Lon = -2.9981,
                            Name = "Axminster"
                        },
                        new
                        {
                            Id = 10,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 50.8842,
                            Lon = -2.7953000000000001,
                            Name = "Crewkerne"
                        },
                        new
                        {
                            Id = 11,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 50.924700000000001,
                            Lon = -2.6132,
                            Name = "Yeovil"
                        },
                        new
                        {
                            Id = 12,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 50.948900000000002,
                            Lon = -2.5198,
                            Name = "Sherborne"
                        },
                        new
                        {
                            Id = 13,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 51.0015,
                            Lon = -2.4154,
                            Name = "Templecombe"
                        },
                        new
                        {
                            Id = 14,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 51.038499999999999,
                            Lon = -2.2768999999999999,
                            Name = "Gillingham (Dorset)"
                        },
                        new
                        {
                            Id = 15,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 51.063899999999997,
                            Lon = -2.0815999999999999,
                            Name = "Tisbury"
                        },
                        new
                        {
                            Id = 16,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 51.069000000000003,
                            Lon = -1.7951999999999999,
                            Name = "Salisbury"
                        },
                        new
                        {
                            Id = 17,
                            Continent = 5,
                            Country = "United Kingdom",
                            Lat = 51.207900000000002,
                            Lon = -1.4795,
                            Name = "Andover"
                        });
                });

            modelBuilder.Entity("TravelAlly.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AcceptsTypes")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Station");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptsTypes = 1,
                            CityId = 1,
                            Code = "SPX",
                            Lat = 51.530000000000001,
                            Lon = -0.125278,
                            Name = "St. Pancras International"
                        },
                        new
                        {
                            Id = 2,
                            AcceptsTypes = 1,
                            CityId = 2,
                            Lat = 48.881110999999997,
                            Lon = 2.3552780000000002,
                            Name = "Gare du Nord"
                        },
                        new
                        {
                            Id = 5,
                            AcceptsTypes = 1,
                            CityId = 4,
                            Code = "BSK",
                            Lat = 51.268419999999999,
                            Lon = -1.08857,
                            Name = "Basingstoke Railway Station"
                        },
                        new
                        {
                            Id = 4,
                            AcceptsTypes = 1,
                            CityId = 3,
                            Code = "WOK",
                            Lat = 51.319029999999998,
                            Lon = -0.55598000000000003,
                            Name = "Woking Railway Station"
                        },
                        new
                        {
                            Id = 3,
                            AcceptsTypes = 1,
                            CityId = 1,
                            Code = "WAT",
                            Lat = 51.503100000000003,
                            Lon = -0.1132,
                            Name = "London Waterloo"
                        },
                        new
                        {
                            Id = 6,
                            AcceptsTypes = 1,
                            CityId = 5,
                            Code = "EXD",
                            Lat = 50.729215500000002,
                            Lon = -3.5435702999999998,
                            Name = "Exeter St. Davids"
                        },
                        new
                        {
                            Id = 20,
                            AcceptsTypes = 1,
                            CityId = 5,
                            Code = "EXC",
                            Lat = 50.7270161,
                            Lon = -3.5321297,
                            Name = "Exeter Central"
                        },
                        new
                        {
                            Id = 7,
                            AcceptsTypes = 1,
                            CityId = 6,
                            Code = "PIN",
                            Lat = 50.737789999999997,
                            Lon = -3.4700799999999998,
                            Name = "Pinhoe Railway Station"
                        },
                        new
                        {
                            Id = 8,
                            AcceptsTypes = 1,
                            CityId = 7,
                            Code = "CBK",
                            Lat = 50.750010000000003,
                            Lon = -3.4209700000000001,
                            Name = "Cranbrook Station"
                        },
                        new
                        {
                            Id = 9,
                            AcceptsTypes = 1,
                            CityId = 8,
                            Code = "HON",
                            Lat = 50.796720000000001,
                            Lon = -3.1869000000000001,
                            Name = "Honiton Railway Station"
                        },
                        new
                        {
                            Id = 10,
                            AcceptsTypes = 1,
                            CityId = 9,
                            Code = "AXM",
                            Lat = 50.77901,
                            Lon = -3.00495,
                            Name = "Axminster Railway Station"
                        },
                        new
                        {
                            Id = 11,
                            AcceptsTypes = 1,
                            CityId = 10,
                            Code = "CKN",
                            Lat = 50.873570000000001,
                            Lon = -2.7784399999999998,
                            Name = "Crewkerne Railway Station"
                        },
                        new
                        {
                            Id = 12,
                            AcceptsTypes = 1,
                            CityId = 11,
                            Code = "YVJ",
                            Lat = 50.924790000000002,
                            Lon = -2.61226,
                            Name = "Yeovil Junction"
                        },
                        new
                        {
                            Id = 13,
                            AcceptsTypes = 1,
                            CityId = 12,
                            Code = "SHE",
                            Lat = 50.943978999999999,
                            Lon = -2.5129695999999999,
                            Name = "Sherborne Railway Station"
                        },
                        new
                        {
                            Id = 14,
                            AcceptsTypes = 1,
                            CityId = 13,
                            Code = "TMC",
                            Lat = 51.00159,
                            Lon = -2.4172799999999999,
                            Name = "Templecombe Railway Station"
                        },
                        new
                        {
                            Id = 15,
                            AcceptsTypes = 1,
                            CityId = 14,
                            Code = "GIL",
                            Lat = 51.034089999999999,
                            Lon = -2.2720799999999999,
                            Name = "Gillingham Railway Station"
                        },
                        new
                        {
                            Id = 16,
                            AcceptsTypes = 1,
                            CityId = 15,
                            Code = "TIS",
                            Lat = 51.061,
                            Lon = -2.0787900000000001,
                            Name = "Tisbury Railway Station"
                        },
                        new
                        {
                            Id = 17,
                            AcceptsTypes = 1,
                            CityId = 16,
                            Code = "SAL",
                            Lat = 51.070549999999997,
                            Lon = -1.8064499999999999,
                            Name = "Salisbury Railway Station"
                        },
                        new
                        {
                            Id = 18,
                            AcceptsTypes = 1,
                            CityId = 17,
                            Code = "ADV",
                            Lat = 51.211550000000003,
                            Lon = -1.4927699999999999,
                            Name = "Andover Railway Station"
                        },
                        new
                        {
                            Id = 19,
                            AcceptsTypes = 1,
                            CityId = 1,
                            Code = "CLJ",
                            Lat = 51.464458899999997,
                            Lon = -0.17051839999999999,
                            Name = "Clapham Junction"
                        });
                });

            modelBuilder.Entity("TravelAlly.Models.StationPassing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("TransportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("TransportId");

                    b.ToTable("StationPassing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartureTime = new DateTime(2023, 2, 27, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            StationId = 5,
                            TransportId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(2023, 2, 27, 9, 8, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 9, 9, 0, 0, DateTimeKind.Unspecified),
                            StationId = 4,
                            TransportId = 1
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new DateTime(2023, 2, 27, 9, 41, 0, 0, DateTimeKind.Unspecified),
                            StationId = 3,
                            TransportId = 1
                        },
                        new
                        {
                            Id = 4,
                            DepartureTime = new DateTime(2023, 2, 27, 10, 34, 0, 0, DateTimeKind.Unspecified),
                            StationId = 1,
                            TransportId = 2
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new DateTime(2023, 2, 27, 15, 8, 0, 0, DateTimeKind.Unspecified),
                            StationId = 2,
                            TransportId = 2
                        },
                        new
                        {
                            Id = 6,
                            DepartureTime = new DateTime(2023, 2, 27, 7, 25, 0, 0, DateTimeKind.Unspecified),
                            StationId = 6,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 7,
                            ArrivalTime = new DateTime(2023, 2, 27, 7, 28, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 7, 29, 0, 0, DateTimeKind.Unspecified),
                            StationId = 20,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 8,
                            ArrivalTime = new DateTime(2023, 2, 27, 7, 33, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 7, 34, 0, 0, DateTimeKind.Unspecified),
                            StationId = 7,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 9,
                            ArrivalTime = new DateTime(2023, 2, 27, 7, 38, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 7, 39, 0, 0, DateTimeKind.Unspecified),
                            StationId = 8,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 10,
                            ArrivalTime = new DateTime(2023, 2, 27, 7, 51, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 7, 52, 0, 0, DateTimeKind.Unspecified),
                            StationId = 9,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 11,
                            ArrivalTime = new DateTime(2023, 2, 27, 8, 3, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 8, 4, 0, 0, DateTimeKind.Unspecified),
                            StationId = 10,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 12,
                            ArrivalTime = new DateTime(2023, 2, 27, 8, 16, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 8, 17, 0, 0, DateTimeKind.Unspecified),
                            StationId = 11,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 13,
                            ArrivalTime = new DateTime(2023, 2, 27, 8, 25, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 8, 26, 0, 0, DateTimeKind.Unspecified),
                            StationId = 12,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 14,
                            ArrivalTime = new DateTime(2023, 2, 27, 8, 35, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 8, 35, 0, 0, DateTimeKind.Unspecified),
                            StationId = 13,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 15,
                            ArrivalTime = new DateTime(2023, 2, 27, 8, 43, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 8, 43, 0, 0, DateTimeKind.Unspecified),
                            StationId = 14,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 16,
                            ArrivalTime = new DateTime(2023, 2, 27, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 8, 51, 0, 0, DateTimeKind.Unspecified),
                            StationId = 15,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 17,
                            ArrivalTime = new DateTime(2023, 2, 27, 9, 1, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 9, 1, 0, 0, DateTimeKind.Unspecified),
                            StationId = 16,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 18,
                            ArrivalTime = new DateTime(2023, 2, 27, 9, 17, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 9, 21, 0, 0, DateTimeKind.Unspecified),
                            StationId = 17,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 19,
                            ArrivalTime = new DateTime(2023, 2, 27, 9, 37, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 9, 38, 0, 0, DateTimeKind.Unspecified),
                            StationId = 18,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 20,
                            ArrivalTime = new DateTime(2023, 2, 27, 9, 56, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 9, 57, 0, 0, DateTimeKind.Unspecified),
                            StationId = 5,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 21,
                            ArrivalTime = new DateTime(2023, 2, 27, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 10, 17, 0, 0, DateTimeKind.Unspecified),
                            StationId = 4,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 22,
                            ArrivalTime = new DateTime(2023, 2, 27, 10, 36, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2023, 2, 27, 10, 37, 0, 0, DateTimeKind.Unspecified),
                            StationId = 19,
                            TransportId = 3
                        },
                        new
                        {
                            Id = 23,
                            ArrivalTime = new DateTime(2023, 2, 27, 10, 49, 0, 0, DateTimeKind.Unspecified),
                            StationId = 3,
                            TransportId = 3
                        });
                });

            modelBuilder.Entity("TravelAlly.Models.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperatesOnDays")
                        .HasColumnType("int");

                    b.Property<string>("RouteCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RouteType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Carrier = "South Western Railway",
                            OperatesOnDays = 21,
                            RouteType = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Carrier = "Eurostar",
                            OperatesOnDays = 127,
                            RouteCode = "",
                            RouteType = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Carrier = "South Western Railway",
                            OperatesOnDays = 127,
                            RouteCode = "",
                            RouteType = 0,
                            Type = 1
                        });
                });

            modelBuilder.Entity("TravelAlly.Models.Station", b =>
                {
                    b.HasOne("TravelAlly.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TravelAlly.Models.StationPassing", b =>
                {
                    b.HasOne("TravelAlly.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAlly.Models.Transport", "Transport")
                        .WithMany("StationPassings")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("TravelAlly.Models.Transport", b =>
                {
                    b.Navigation("StationPassings");
                });
#pragma warning restore 612, 618
        }
    }
}
